# Generated by Django 5.1.7 on 2025-03-28 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano_lancamento', models.IntegerField(max_length=4)),
                ('estudio', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('sinopse', models.TextField()),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
