# Generated by Django 5.1.7 on 2025-05-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_usuario_imagem'),
        ('sistema', '0004_usuario_imagem'),
    ]

    operations = [
    ]
